### ISSUE TITLE
Consider altsnap

### ISSUE THREAD

**Issue by NotAkitake** [alvesvaren/resizer2#6]
Very similar goals, more features, also free and open source
https://github.com/RamonUnch/AltSnap

**Comment by alvesvaren** [comment]
Yes AltSnap is similar. But this one doesn't try to do as much, just resizing and moving (opacity + minimizing/restoring) windows and only tries to support the latest windows version. Because of that it is much lighter on resources.
It also updates the system cursor which makes it feel a bit less janky imo :)
